news_sites:
  eltiempo:
    url: https://www.eltiempo.com/
    queries:
      homepage_article_links: 'a.title.page-link'
      article_body: 'p.contenido'
      article_title: 'h1.titulo'
  semana:
    url: https://www.semana.com/
    queries:
      homepage_article_links: 'h2.article-h a'
      article_body: 'div#contentItem p'
      article_title: 'a.article-h-link'